# Generated by Django 3.0.2 on 2020-01-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelRelationship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productstatus', to='ModelRelationship.Customer'),
        ),
    ]
