# Generated by Django 3.0.2 on 2020-02-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelRelationship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ManyToManyField(to='ModelRelationship.Customer'),
        ),
    ]
